services:
  directory:
    build:
      context: ./directory-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  # A single Charger Service
  charger-1:
    build:
      context: ./charger-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DIRECTORY_ENDPOINT=http://directory:8000/directory
      - CHARGER_ENDPOINT=http://charger:8080/charger
      - NUM_CHARGE_POINTS=2
      - MAX_EFFEKT_KILOWATT=11
      - CHARGER_NAME=charger_1

      # HINT: The other halves of this task live inside Charger.java and RegisterRequest.java.
    volumes:
      - ./charger-service/frontend:/app/charger-service/frontend

  charger-2:
    build:
      context: ./charger-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - DIRECTORY_ENDPOINT=http://directory:8000/directory
      - CHARGER_ENDPOINT=http://charger:8080/charger
      - NUM_CHARGE_POINTS=3
      - MAX_EFFEKT_KILOWATT=12
      - CHARGER_NAME=charger_2
      # HINT: The other halves of this task live inside Charger.java and RegisterRequest.java.
    volumes:
      - ./charger-service/frontend:/app/charger-service/frontend



  charger-3:
    build:
      context: ./charger-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - DIRECTORY_ENDPOINT=http://directory:8000/directory
      - CHARGER_ENDPOINT=http://charger:8080/charger
      - NUM_CHARGE_POINTS=4
      - MAX_EFFEKT_KILOWATT=13
      - CHARGER_NAME=charger_3

      # HINT: The other halves of this task live inside Charger.java and RegisterRequest.java.
    volumes:
      - ./charger-service/frontend:/app/charger-service/frontend
