services:
  directory:
    build:
      context: ./directory-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  # A single Charger Service
  charger-1:
    build:
      context: ./charger-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DIRECTORY_ENDPOINT=http://directory:8000/directory
      - CHARGER_ENDPOINT=http://charger:8080/charger
      # FIXME: Create the environment variable `NUM_CHARGE_POINTS` and assign to it a positive number.
      # HINT: The other halves of this task live inside Charger.java and RegisterRequest.java.
    volumes:
      - ./charger-service/frontend:/app/charger-service/frontend

  charger-2:
    build:
      context: ./charger-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - DIRECTORY_ENDPOINT=http://directory:8000/directory
      - CHARGER_ENDPOINT=http://charger:8080/charger
      # FIXME: Create the environment variable `NUM_CHARGE_POINTS` and assign to it a positive number.
      # HINT: The other halves of this task live inside Charger.java and RegisterRequest.java.
    volumes:
      - ./charger-service/frontend:/app/charger-service/frontend
