[package]
name = "directory-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "*" }
chrono = { version = "*", features = ["serde"] }
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
tokio = { version = "*", features = ["full"] }
